# Generated by Django 4.2 on 2023-04-08 13:01

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('Github', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=130)),
                ('timeStamp', models.DateTimeField(blank=True)),
                ('category', models.CharField(default='', max_length=59)),
                ('subcategory', models.CharField(default='', max_length=57)),
                ('image', models.FileField(default='', upload_to='post/images/')),
                ('overview', models.TextField()),
                ('post_desc', tinymce.models.HTMLField(default='0')),
            ],
        ),
    ]
